### ISSUE TITLE
Add cargo and associated tools from rules_rust to the example

### ISSUE THREAD

**Issue by scasagrande** [buildbuddy-io/bazel_env.bzl#23]
Rust is pretty common, it would be nice for the [example](https://github.com/buildbuddy-io/bazel_env.bzl/blob/main/examples/BUILD.bazel) to be expanded to include `cargo` et al from `rules_rust`.

**Comment by fmeum** [comment]
Sounds reasonable, would you be interested in sending a PR?

**Comment by scasagrande** [comment]
Absolutely

once I figure it out 😄

**Comment by scasagrande** [comment]
Turns out the fix was minor, so I have a PR open now
